### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by AndrewZhang233** [CoderMusou/MECT4CNER#10]
AdaptionSelfAttention.py中
 if dataset == 'weibo':
            self.randomAttention = nn.Parameter(torch.empty(1, self.num_heads, 320, 320), requires_grad=True)
        if dataset == 'msra':
            self.randomAttention = nn.Parameter(torch.empty(1, self.num_heads, 310, 310), requires_grad=True)
        if dataset == 'resume':
            self.randomAttention = nn.Parameter(torch.empty(1, self.num_heads, 344, 344), requires_grad=True)
中的320 ，310，344是由什么决定的？若是换成自己的语料需要改哪些部分的代码？

**Comment by CoderMusou** [comment]
这是由数据集中最大样本长度决定的。
