### ISSUE TITLE
[main.py]IndexError: list index out of range

### ISSUE THREAD

**Issue by mayixuan1219** [CoderMusou/MECT4CNER#11]
When running"python main.py --dataset weibo" there is an "IndexError: list index out of range", which is directly caused by  "return list(c_info[3])"  in  \MECT4CNER\Modules\CNNRadicalLevelEmbedding.py, line 26, in char2radical (a function defined in the certain file).

I'm wondering why choose the number"3",  and how I should do to solve the error.

**Comment by CoderMusou** [comment]
Please see the [issue 6](https://github.com/CoderMusou/MECT4CNER/issues/6#issuecomment-976575928).

**Comment by mayixuan1219** [comment]
I use [https://github.com/kfcd/chaizi](https://github.com/kfcd/chaizi)  but I'm wodering if I should replace index 3 with 0 rather than 1
the c_info[0]s are:
白 勺
手 戈
一 丿 丨 丶
乛 亅
日 疋
人 尔
口 合
丿 乀
一 丿 月
女 子
一 人 土   
and so on

**Comment by CoderMusou** [comment]
You are right. I forgot that char is used as the key of the Dict() in the code. Thanks!

The correct way is to replace 3 with 0.

**Comment by mayixuan1219** [comment]
THANK U !
