### ISSUE TITLE
MSRA数据集

### ISSUE THREAD

**Issue by Coder-XIAOKAI** [CoderMusou/MECT4CNER#13]
限制样本长度为200的msra数据集使用的是单独处理后的数据集吗，能否分享一份处理好的数据集，我对数据集进行处理后16G显存依旧不足，batch为5
邮箱：1256422591@qq.com
非常感谢！！！

**Comment by CoderMusou** [comment]
请阅读[README.md](https://github.com/CoderMusou/MECT4CNER#readme)，源码中有切分脚本：
```
python Utils/preprocess.py --clip_msra
```
