### ISSUE TITLE
请问为啥设置100个epoch，跑的时候确只有50个epoch，改成别的数字也不起作用

### ISSUE THREAD

**Issue by yangyang-wu** [CoderMusou/MECT4CNER#20]

**Comment by CoderMusou** [comment]
您好，请问你是改那一行的？我在247-298行固定了每个数据集的超参，那里有对应数据集的epoch。

**Comment by yangyang-wu** [comment]
> 您好，请问你是改那一行的？我在247-298行固定了每个数据集的超参，那里有对应数据集的epoch。

我刚刚只看到default那部分，没注意247-298行，现在懂了，谢谢您
