### ISSUE TITLE
weibo数据集精度没有成功复现

### ISSUE THREAD

**Issue by rongjunlee** [CoderMusou/MECT4CNER#4]
请问，使用漢語拆字字典得到weibo数据集的精度如下，是正常的么？
[tester] 
SpanFPreRecMetric: f=0.574386, pre=0.625352, rec=0.5311
label_acc: acc=0.957296
{'SpanFPreRecMetric': {'f': 0.574386, 'pre': 0.625352, 'rec': 0.5311}, 'label_acc': {'acc': 0.957296}}

离论文中63.30，相差很大。

**Comment by CoderMusou** [comment]
漢語拆字字典中的拆字方法其实和论文中实际用的'汉字部件构造'差别较大。例如，汉字【榆】两种拆字方式分别对应
> [漢語拆字字典](https://github.com/kfcd/chaizi/blob/master/chaizi-jt.txt#L6128)：木 俞
> [汉程字典](http://tool.httpcn.com/Html/Zi/28/PWMEAZCQILTBRNXVTB.shtml)：木人一月刂

相当于只用了论文中提到的首尾分解拆字方式，而汉字部件构造所包含的信息要更加丰富。实验中我也用过漢語拆字字典的方式，精度确实没有带来更多提升，由于版权原因Readme中提到了用漢語拆字字典的替换方案，但不保证能复现论文结果。另外由于weibo数据集比较小，数据差异比较大，随机波动可能也会影响最终表现。
如果想要复现论文中结果，建议想办法尝试用‘汉字部件构造’去跑模型。

**Comment by rongjunlee** [comment]
感谢快速和详细的回复

**Comment by cabbageNoob** [comment]
2022/04/12 21:43:48 - trainer - [INFO] - 
In Epoch:40/Step:5400, got best dev performance:
2022/04/12 21:43:48 - trainer - [INFO] - SpanFPreRecMetric: f=0.652095, pre=0.665428, rec=0.639286
label_acc: acc=0.959862
2022/04/12 21:43:48 - trainer - [INFO] - Reloaded the best model.
2022/04/12 21:43:48 - tester - [INFO] - Evaluate data in 0.9 seconds!
2022/04/12 21:43:48 - tester - [INFO] - [tester] 
SpanFPreRecMetric: f=0.583639, pre=0.600503, rec=0.567696
label_acc: acc=0.956659

敢	工攵(gongwen)	乙耳攵
散	艹攵(caowen)	月攵
敦	享攵(xiangwen)	亠口子攵
敬	苟攵(gouwen)	艹勹口攵
数	娄攵(louwen)	米女攵
敲	高攴(gaopu)	亠口冂口卜又

您好，我使用爬虫获取了 汉字部件构造，上面有个别示例，跑weibo数据时候，在验证集上最好达到了65，但在测试集上f1值只有58多，没有达到论文指标，方便给一下代码里的chars_info.txt的个别示例吗，我看看格式与我爬取的汉字部件构造有啥不一样的地方

**Comment by CoderMusou** [comment]
您这个结果只有58确实有点低了，示例中最后一列的结构部件与论文中所用的一致，您只用了最后一列的汉字结构部件吗？weibo这个数据集非常小，结果波动会比较大，可以尝试换随机种子多跑几次。

**Comment by cabbageNoob** [comment]
确实只用了最后一列的汉字结构部件，其他超参数用的代码里的，未改动，另外请问一下，代码里char2radical函数，返回的列表是笔画之间有空格的吗，即：char2radical('敲')，返回的是['亠', ' ', '口', ' ', '冂', ' ', '口', ' ', '卜', ' ', '又']，还是['亠',  '口',  '冂',  '口',  '卜',  '又']，其实这两个我都跑了一遍，加上空格的话效果才会到58到59之间，不加空格只有55左右了

**Comment by CoderMusou** [comment]
机器不同，软件版本不同，都可能会造成随机初始化的参数不同。你可以检查一下`radical_encoder.transformer_layer.attn.u`中的参数是否跟我机器上初始化的结果一样：
```
tensor([[-0.3361,  0.0899, -0.4741,  0.2254, -0.2680,  0.2848,  0.1585,  0.3441,
         -0.1998,  0.0246,  0.0381,  0.4811, -0.2814,  0.2904, -0.1586,  0.4663],
        [-0.3207, -0.2801, -0.0024, -0.4180,  0.3434,  0.1258, -0.0371,  0.3966,
         -0.4512, -0.2878,  0.0063,  0.1167, -0.3245, -0.4915,  0.2686,  0.4706],
        [ 0.0039,  0.1041,  0.3609, -0.2252,  0.0873,  0.1030, -0.3899, -0.1419,
          0.2941, -0.4517,  0.1434, -0.2918,  0.2736,  0.4195, -0.3808, -0.1394],
        [-0.0587,  0.3445,  0.2402, -0.3008,  0.3099, -0.1781,  0.1863, -0.2786,
          0.2509,  0.4856, -0.4683, -0.1186, -0.0225, -0.1414, -0.1037, -0.0028],
        [-0.2687,  0.2115,  0.1794,  0.2589,  0.4684,  0.4015, -0.2157, -0.3329,
          0.3600,  0.2090, -0.2367, -0.3043,  0.4208,  0.4235, -0.3716, -0.2534],
        [ 0.3810,  0.4606,  0.3187, -0.2376,  0.3817, -0.4072,  0.3556,  0.1669,
          0.2689,  0.3457, -0.0775,  0.3368, -0.1405, -0.4947, -0.2815, -0.0384],
        [-0.4686,  0.3623,  0.3381,  0.4989, -0.1179,  0.4661,  0.1381, -0.3305,
          0.0367,  0.1774, -0.4111,  0.2138, -0.1611, -0.1100,  0.3833, -0.0230],
        [-0.0206,  0.0286, -0.0505, -0.2729,  0.0787, -0.4712, -0.0804, -0.1666,
          0.3572,  0.3767,  0.3468, -0.4631,  0.3946,  0.4035,  0.0231, -0.0254]])
```
如果不一样，可以尝试跑跑其他随机种子，weibo这个数据集很小波动确实会很大。建议在ontonotes上验证一下。
