### ISSUE TITLE
program of the code

### ISSUE THREAD

**Issue by kbprogrammer-tech** [CoderMusou/MECT4CNER#6]
I want to know on line 26 of CNNRadicalLevelEmbedding.py： return list(c_info[3])，is there a problem？I generated more than a list in the running code.So I changed this to：return list(c_info[:3]),I don't know if this is right. I hope to answer it,thk

**Comment by CoderMusou** [comment]
Because the Chinese character component I used contains several columns of information, among which c_info[3] corresponds to the structural components in the paper. If you use https://github.com/kfcd/chaizi, you can replace index 3 with 0.

**Comment by kbprogrammer-tech** [comment]
thanks
