### ISSUE TITLE
BERT+MECT

### ISSUE THREAD

**Issue by xinhai-zhu** [CoderMusou/MECT4CNER#8]
您好，请问可以开源带BERT的MECT代码吗，想学习一下，感谢

**Comment by CoderMusou** [comment]
您好，论文中有关BERT的实验代码和FLAT公开的源码基本一致，主要在Emebedding层做了修改，具体实现可以参考FLAT/V1中的代码，这里不打算更新这部分代码了。

**Comment by zzq-810** [comment]
> 您好，请问可以开源带BERT的MECT代码吗，想学习一下，感谢

你好，你找到了吗，可以分享一下吗，感谢
